log_dir: "/mnt/cg_storage/msg_brokers_log_{{inventory_hostname}}"
gluster_volume: cg_storage
# these are options for init.d service script 
daemon: /home/cg/msg_brokers
pidfile: /var/run/msg_brokers.pid
daemon_opts: "-config=/home/cg/msg_brokers.conf  -log_dir={{log_dir}} -v=0 2>{{log_dir}}/stderr_{{ansible_date_time.date}}_{{ansible_date_time.time}}.log "
service_name: msg_brokers
