- name: Run tasks on current ansible localhost
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: build backend workers binary
    shell: go build         -o /tmp/backend_worker /home/cg/code/code-grep/src/backend/backend_worker.go
    environment:
      PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
      GOPATH: /home/cg/code/code-grep


- hosts: workers
  user: cg
  sudo: yes
  roles: 
  - worker

